#!/usr/bin/expect --

# send -- "firefox 'https://nagios/cgi-bin/extinfo.cgi?type=2&host=jsat-admt1&service=FIT+VPN+-+Peer+IP+163.118.252.61'\r"
# expect $prompt
# send -- "firefox 'https://nagios/cgi-bin/cmd.cgi?cmd_typ=7&host=jsat-admt1&service=FIT+VPN+-+Peer+IP+163.118.252.61&force_check'\r"
# expect $prompt
# # send -- "ps aux | grep \$PPID | awk \'\$0~/expect/ \{cmd=\"skill -9 \" \$7 \"\\n\"\;cmd|&getline\}'\r"
# send -- "ps aux | grep \$PPID | awk \'\$0~/expect/ \{cmd=\"skill -9 \" \$7 \"\\n\"\;print cmd\}'\r"
# expect -re {skill -9 pts/.}

set workstation {bryanxp}
set user        "DCO\\$env(USER)"
set prompt      {^.* $}
set service     {ColdFusion MX 7 Application Server}
set timeout     {-1}
set hostname    [lindex $argv 0]
set password    [exec grep pass /home/bharris/.neoconfig | head -1 | cut -d= -f2 | tr -d " "]

if {$hostname == "web103"} {
    set server {\\10.2.52.130}
    set share "$server\\ipc$"
} elseif {$hostname == "foobar"} {
    set server {\\4.2.2.2}
    set share "$server\\ipc$"
}

spawn $env(SHELL)
expect -re $prompt
send -- "ssh $workstation\r"
expect -re $prompt
send "stty -echo\r"
expect -re $prompt
send "net use '$share' '/user:$user' '$password'\r"
expect "The command completed successfully."
send "stty echo\r"
expect -re $prompt

# # Stop
# send "sc '$server' 'stop' 'ColdFusion MX 7 Application Server'\r"

# # Make sure
# set x 0
# while {$x==0} {
#     send "sc '$server' 'query' 'ColdFusion MX 7 Application Server'\r"
#     expect {
#         -re {.*STATE.*RUNNING} {
#             sleep .5
#             expect -re $prompt
#         }
#         -re {.*STATE.*STOPPED} {
#             set x 1
#             expect -re $prompt
#         }
#     }
# }

# # Start
# send "sc '$server' 'start' 'ColdFusion MX 7 Application Server'\r"

# Make sure
set x 0
while {$x==0} {
    send "sc '$server' 'query' 'ColdFusion MX 7 Application Server'\r"
    expect {
        -re {STATE.*STOPPED} {
            sleep .5
            expect -re $prompt
        }
        -re {STATE.*RUNNING} {
            set x 1
            expect -re $prompt
        }
    }
}

send "net use '/d' '$share'\r"
expect -re $prompt
send "logout\r"
expect "Connection to $workstation closed."
exit
