#!/usr/bin/expect -f

# WARNING
#
# The last line kills the parent (I think), comment it for safety
#  From an xterm it might be okay
#  From cron I believe it will kill your whole X11 session
#
# WARNING

set user        "bharris"
set prompt      "$ "
set pixcmd      "neo pix "
set fwip        "10.2.199.1"
set hostname    "dal1-jsa-fw1/pri/act"
set sshargs     "-v -k -t -2 -4 -a -q -x -p 22 -l $user"
set timeout -1
append sshargs  " -o StrictHostKeyChecking=no"
append sshargs  " -o Compression=no"
append sshargs  " -o CheckHostIP=no"
append sshargs  " -o PasswordAuthentication=yes"
append sshargs  " -o PubkeyAuthentication=no"
append sshargs  " -o RhostsRSAAuthentication=no"
append sshargs  " -o RSAAuthentication=no"



  spawn $env(SHELL)
  expect $prompt




send -- "$pixcmd $fwip\r"
  expect "\r$hostname> en\r\r"
  expect "Password: *********\r\r"
  expect "\r$hostname# "
send -- "clear isa sa 163.118.252.61\r"
  expect "# "
send -- "exit\r"
  expect $prompt

send -- "ssh 10.2.199.21 ping -c5 172.16.22.129\r"
  expect "PING 172.16.22.129 (172.16.22.129) 56(84) bytes of data.\r"

set x 0; while {$x==0} {
  expect {
    -re {64 bytes from 172\.16\.22\.129: icmp_seq=[0-9]+ ttl=128 time=[0-9]+\.[0-9]+ ms} { }
    -re {--- 172\.16\.22\.129 ping statistics ---} { set x 1 }
  }
}
  expect -re {[0-9] packets transmitted, [0-9] received, [0-9]+% packet loss, time [0-9]+ms}
  expect -re {rtt min/avg/max/mdev = [0-9]+\.[0-9]+/[0-9]+\.[0-9]+/[0-9]+\.[0-9]+/[0-9]+\.[0-9]+ ms}
  expect $prompt

  expect $prompt
send -- "firefox 'https://nagios/cgi-bin/extinfo.cgi?type=2&host=jsat-admt1&service=FIT+VPN+-+Peer+IP+163.118.252.61'\r"
  expect $prompt
send -- "ps aux | grep \$PPID | awk \'\$0~/expect/ \{cmd=\"skill -9 \" \$7 \"\\n\"\;cmd|&getline\}'\r"
  expect eof

send -- "firefox 'https://nagios/cgi-bin/cmd.cgi?cmd_typ=7&host=jsat-admt1&service=FIT+VPN+-+Peer+IP+163.118.252.61&force_check'\r"
