#!/bin/bash

( cd /var/spool/mqueue
  queues=$(for i in $(echo * | xargs -n 1 | egrep -v '^df$|^qf$|^xf$'); do
    echo ${i%?}
  done | sort | uniq)
  for name in ${queues[@]}; do
    numberOfEmails=`find $name?/qf -type f | wc -l`
    sizeOfEmails='';
    for file in `find $name?/df/ -type f`; do ((sizeOfEmails+=$(stat -c%s "$file"))); done
    if test -z $sizeOfEmails; then sizeOfEmails="0"; fi
    printf "%s,%s,%s\n" $name $numberOfEmails $sizeOfEmails
  done
)

exit 0
