#! /usr/bin/gawk --exec

BEGIN \
{
  if((ARGV[1] == "--help") || (ARGV[1] == "-h")) {
  printf "q: display queue info\n\n\n"
  printf "usage: q [ \"--help\" | \"-h\" | \"--all\" | \"-a\" ] [ name ... ]\n\n"
  printf "--help or -h: print this message\n"
  printf "--all or -a: print all queues, even empty ones\n\n"
  printf "Queue name does not have to be literal, the script will print any matches it finds."
  printf "  Showing all queues excludes empty queues (ones with zero emails).\n\n"
  printf "EXAMPLES\n"
  printf "Example usage for Typhoon would be: q typhoon\n"
  printf "Example usage for all usmc queues would be q usmc\n"
  printf "Example usage for all queues except empty would be: q\n"
  printf "Example usage for all queues even empty would be: q --all\n"
  exit
  }

  IGNORECASE=1
  FS=","
  cmd="nc xx.xx.xx.151 7257"
  i=0
  while((cmd|&getline)>0) {
    name=$1
    emails=$2
    bytes=$3
    names[i++]=name
    emailsIms01[name]=emails
    bytesIms01[name]=bytes
  }
  close(cmd)

  cmd="nc xx.xx.xx.152 7257"
  while((cmd|&getline)>0) {
    name=$1
    emails=$2
    bytes=$3
    emailsIms02[name]=emails
    bytesIms02[name]=bytes
  }
  close(cmd)

  cmd="nc xx.xx.xx.153 7257"
  while((cmd|&getline)>0) {
    name=$1
    emails=$2
    bytes=$3
    emailsIms03[name]=emails
    bytesIms03[name]=bytes
  }
  close(cmd)
  FS=" "

  if (ARGV[1] && ARGV[1] !~ /\-/) {
    printf "%-27s", "Queue Name"
    printf "%-13s", "IMS01 Emails"
    printf "%-13s", "IMS01 Bytes"
    printf "%-13s", "IMS02 Emails"
    printf "%-13s", "IMS02 Bytes"
    printf "%-13s", "IMS03 Emails"
    printf "%-13s", "IMS03 Bytes"
    printf "%-13s", "Total Emails"
    printf "%-13s\n", "Total Bytes"
    searchString=ARGV[1]
    for (var in names) {
      if (names[var] ~ ARGV[1]) {
        totalEmails=emailsIms01[names[var]] + emailsIms02[names[var]] + emailsIms03[names[var]]
        totalBytes=bytesIms01[names[var]] + bytesIms02[names[var]] + bytesIms03[names[var]]
        printf "%-27s", names[var]
        printf "%-13s", emailsIms01[names[var]]
        printf "%-13s", bytesIms01[names[var]]
        printf "%-13s", emailsIms02[names[var]]
        printf "%-13s", bytesIms02[names[var]]
        printf "%-13s", emailsIms03[names[var]]
        printf "%-13s", bytesIms03[names[var]]
        printf "%-13s", totalEmails
        printf "%-13s\n", totalBytes
      }
    }
    exit
  }

  printf "%-27s", "Queue Name"
  printf "%-13s", "IMS01 Emails"
  printf "%-13s", "IMS01 Bytes"
  printf "%-13s", "IMS02 Emails"
  printf "%-13s", "IMS02 Bytes"
  printf "%-13s", "IMS03 Emails"
  printf "%-13s", "IMS03 Bytes"
  printf "%-13s", "Total Emails"
  printf "%-13s\n", "Total Bytes"
  for (var in names) {
    totalEmails=emailsIms01[names[var]] + emailsIms02[names[var]] + emailsIms03[names[var]]
    totalBytes=bytesIms01[names[var]] + bytesIms02[names[var]] + bytesIms03[names[var]]
    if(ARGV[1] != "-a")
      if(ARGV[1] != "--all")
        if(totalEmails == 0)
          continue
    printf "%-27s", names[var]
    printf "%-13s", emailsIms01[names[var]]
    printf "%-13s", bytesIms01[names[var]]
    printf "%-13s", emailsIms02[names[var]]
    printf "%-13s", bytesIms02[names[var]]
    printf "%-13s", emailsIms03[names[var]]
    printf "%-13s", bytesIms03[names[var]]
    printf "%-13s", totalEmails
    printf "%-13s\n", totalBytes
  }

}
