#!/usr/bin/expect --

set hostname [lindex $argv 0]
set service [lindex $argv 1]

if {$hostname == "app5"} {
    set ip      "66.111.107.47"
    set domain  "volunteersolutions.org"
} elseif {$hostname == "vqa1"} {
    set ip      "67.208.33.199"
    set domain  "volunteersolutions.org"
} elseif {$hostname == "app1"} {
    set ip      "66.111.105.218"
    set domain  "volunteersolutions.org"
} elseif {$hostname == "vmapp1"} {
    set ip      "66.111.110.21"
    set domain  "volunteersolutions.org"
} elseif {$hostname == "app4"} {
    set ip      "66.111.105.219"
    set domain  "volunteersolutions.org"
}

if {$service == "solr-slave"} {
    set cmd     {svc -k }
    append cmd  $service
} elseif {$service == "solr-master"} {
    set cmd     {svc -k }
    append cmd  $service
} elseif {$service == "qa-task"} {
    set cmd     {svc -k }
    append cmd  $service
} elseif {$service == "va-task-1"} {
    set cmd     {svc -k }
    append cmd  $service
} elseif {$service == "va-task-2"} {
    set cmd     {svc -k }
    append cmd  $service
} elseif {$service == "vs-1"} {
    set cmd     {svc -k }
    append cmd  $service
} elseif {$service == "vs-2"} {
    set cmd     {svc -k }
    append cmd  $service
} else {
    set cmd {svc -k $(ps -eo vsize,args|sort -n|awk '$2 ~ /nsd/ {print $4}'|awk -F"/" '{print $NF}'|cut -d. -f1|tail -1)}
}

set timeout -1
spawn ssh $ip
match_max 100000

send -- "exec sudo su -s /bin/bash -\r"
  expect -exact "exec sudo su -s /bin/bash -\r"
  expect -exact "$hostname:~# "
send -- "cd /service/\r"
  expect -exact "cd /service/\r"
  expect -exact "$hostname:/service# "
send -- "$cmd\r"
  expect -exact "$hostname:/service# "
send -- ""
  expect -exact "logout\r"
  expect eof
